### ISSUE TITLE
Nav bar tweaks

### ISSUE THREAD

**Issue by arthurHarding** [cooperation-hull/CooperationHullMainSite#122]
Jane has highlighted that nav bar goes off to the side on wide screens.

![Image](https://github.com/Fireflower2012/CooperationHullMainSite/assets/17554549/22bb88c8-87d2-4375-9d7c-fd6f025db6a4)

Also the hamburger has a white background. Can we drop that?

![Image](https://github.com/Fireflower2012/CooperationHullMainSite/assets/17554549/07e4b0de-99ce-48ee-9b27-c361f1ec4d88)

**Comment by lewis-conroy** [comment]
Hamburger BG is fixed - did we say that the other issue with wide screens was fixed already along the way?

**Comment by arthurHarding** [comment]
![Image](https://github.com/Fireflower2012/CooperationHullMainSite/assets/17554549/f428f3fc-a4ad-4202-8d4a-87657400636c)

but maybe we can make the nav bar the same width as the content here

**Comment by lewis-conroy** [comment]
![Image](https://github.com/cooperation-hull/CooperationHullMainSite/assets/69333515/d2ce082e-26fa-4df9-8f72-69c9db7a6f57)

Seems to be working on my end. Can you still reproduce this issue?

**Comment by lewis-conroy** [comment]
the dropdown menu is still white - any idea how we can improve that? Making it the same colour as the hero might look a bit dodgy

**Comment by arthurHarding** [comment]
Maybe a translucent box that also surrounds the hamburger icon (when the menu is open)?
