### ISSUE TITLE
Nav bar logo on content pages display issue

### ISSUE THREAD

**Issue by Fireflower2012** [cooperation-hull/CooperationHullMainSite#133]
![Image](https://github.com/Fireflower2012/CooperationHullMainSite/assets/7806502/ec3156b9-4999-4070-be6d-5c42abb24bc5)

Now the nav bar is transpsrant the logo is 'invisible' on content pages as it's exactly the same shade as the page background

**Comment by arthurHarding** [comment]
In the long run I might like to make the content pages white. So maybe the answer is make the logo black on all pages for now, and when we update the content pages change it back to orange

**Comment by lewis-conroy** [comment]
Fixed in #150 :)
